# Generated by Django 4.0.3 on 2022-03-26 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_pub_date_alter_image_img_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
