# Generated by Django 4.0.3 on 2022-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no-image', upload_to='photo/'),
        ),
    ]
